# Generated by Django 2.2 on 2019-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='/media/images/765-default-avatar.png', null=True, upload_to='media/images/'),
        ),
    ]
