# Generated by Django 2.2 on 2019-04-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190418_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='main.Profile'),
        ),
    ]
