# Generated by Django 2.2 on 2019-04-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_groupchat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GroupChat'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PrivateChat'),
        ),
    ]
