# Generated by Django 2.2 on 2019-04-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190427_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='profile',
            new_name='profiles',
        ),
    ]
